#!/bin/sh
branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "Commit to the main branch rejected"
  exit 1
fi

if [ -n "$MINWARE_PRECOMMIT_ENABLE" ]; then
  npm run lint:fix
fi
